import type { Capability } from "../core/types.ts";
import type { SkillRouterConfig } from "../config/config.ts";
import { computeRisk } from "../security/risk.ts";

export interface DashboardRow {
  id: string;
  task: string;
  activations: string[];
  deactivations: string[];
  timestamp: string;
}

export interface DashboardData {
  rows: DashboardRow[];
  capabilities: Capability[];
  installed: Array<{ id: string; state: string }>;
  config: SkillRouterConfig;
}

export function exportDashboard(data: DashboardData): string {
  const rowsHtml = data.rows.map((row) => {
    const act = row.activations.map((a) => `<span class="tag act">${escapeHtml(a)}</span>`).join("");
    const deact = row.deactivations.map((a) => `<span class="tag deact">${escapeHtml(a)}</span>`).join("");
    return `<tr>
      <td class="mono">${escapeHtml(row.id)}</td>
      <td>${escapeHtml(row.task)}</td>
      <td>${act || "<span class='muted'>—</span>"}</td>
      <td>${deact || "<span class='muted'>—</span>"}</td>
      <td class="mono muted">${escapeHtml(row.timestamp)}</td>
    </tr>`;
  }).join("\n");

  const capRows = data.capabilities.map((capability) => {
    const risk = computeRisk(capability);
    return `<tr>
      <td class="mono">${escapeHtml(capability.id)}</td>
      <td>${escapeHtml(capability.name)}</td>
      <td><span class="risk risk-${risk.level}">${escapeHtml(risk.level.toUpperCase())}</span></td>
      <td>${escapeHtml((capability.description ?? "").slice(0, 80))}</td>
    </tr>`;
  }).join("\n");

  const installed = data.installed.map((i) => `<span class="tag ${i.state.toLowerCase()}">${escapeHtml(i.id)}</span>`).join(" ");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>SkillRouter — Decision Dashboard</title>
<style>
  :root { color-scheme: dark; }
  body { font-family: system-ui, sans-serif; margin: 2rem; background: #0d1117; color: #c9d1d9; }
  h1 { color: #f0f6fc; }
  h2 { color: #8b949e; margin-top: 2.5rem; font-size: 1rem; text-transform: uppercase; letter-spacing: .05em; }
  table { border-collapse: collapse; width: 100%; margin-top: .5rem; }
  th, td { text-align: left; padding: .45rem .6rem; border-bottom: 1px solid #21262d; font-size: .875rem; vertical-align: top; }
  th { color: #8b949e; font-weight: 600; }
  .mono { font-family: ui-monospace, monospace; font-size: .8rem; }
  .muted { color: #8b949e; }
  .tag { display: inline-block; padding: .1rem .45rem; border-radius: 999px; font-size: .72rem; margin-right: .3rem; background: #21262d; color: #c9d1d9; }
  .tag.act { background: #1f6feb33; color: #58a6ff; }
  .tag.deact { background: #bc4c0033; color: #d29922; }
  .tag.active { background: #2ea04333; color: #3fb950; }
  .tag.enabled { background: #1f6feb33; color: #58a6ff; }
  .risk { font-size: .7rem; font-weight: 700; padding: .1rem .4rem; border-radius: 4px; }
  .risk-low { color: #3fb950; background: #2ea0431a; }
  .risk-medium { color: #d29922; background: #bc4c001a; }
  .risk-high, .risk-critical { color: #f85149; background: #da36331a; }
  .summary { display: flex; gap: 2rem; margin: 1rem 0 2rem; }
  .summary .box { border: 1px solid #21262d; border-radius: 8px; padding: .75rem 1.25rem; }
  .summary .num { font-size: 1.5rem; font-weight: 700; color: #f0f6fc; }
  .summary .label { font-size: .75rem; color: #8b949e; }
  footer { margin-top: 3rem; color: #484f58; font-size: .75rem; }
</style>
</head>
<body>
<h1>SkillRouter — Decision Dashboard</h1>
<p class="muted">Routing decisions, capabilities, and security posture at a glance.</p>
<div class="summary">
  <div class="box"><div class="num">${data.rows.length}</div><div class="label">decisions</div></div>
  <div class="box"><div class="num">${data.capabilities.length}</div><div class="label">known capabilities</div></div>
  <div class="box"><div class="num">${data.installed.length}</div><div class="label">installed</div></div>
  <div class="box"><div class="num">${modeLabel(data.config)}</div><div class="label">router mode</div></div>
</div>
<h2>Installed capabilities</h2>
<p>${installed || '<span class="muted">none</span>'}</p>
<h2>Recent decisions</h2>
<table>
  <thead><tr><th>id</th><th>task</th><th>activated</th><th>deactivated</th><th>when</th></tr></thead>
  <tbody>
${rowsHtml || '<tr><td colspan="5" class="muted">No decisions recorded yet.</td></tr>'}
  </tbody>
</table>
<h2>Capability registry</h2>
<table>
  <thead><tr><th>id</th><th>name</th><th>risk</th><th>description</th></tr></thead>
  <tbody>
${capRows || '<tr><td colspan="4" class="muted">Registry empty.</td></tr>'}
  </tbody>
</table>
<footer>Generated by SkillRouter. Static snapshot — refresh by re-running <code>skillrouter export</code>.</footer>
</body>
</html>
`;
}

function modeLabel(config: SkillRouterConfig): string {
  return config.router.mode.toUpperCase();
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}